services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mariadb-custom
    container_name: db
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  web1:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr-app
    container_name: web1
    environment:
      - DB_HOST=db
    networks:
      - backend
      - frontend

  web2:
    image: qr-app
    container_name: web2
    environment:
      - DB_HOST=db
    networks:
      - backend
      - frontend

  haproxy:
    build:
      context: .
      dockerfile: Dockerfile.haproxy
    image: haproxy-custom
    container_name: haproxy
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
    networks:
      - frontend

volumes:
  mariadb-data:

networks:
  frontend:
  backend:
