apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init
  namespace: qr-survey
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS survey_db;

    USE survey_db;

    CREATE TABLE IF NOT EXISTS surveys (
      id INT AUTO_INCREMENT PRIMARY KEY,
      question TEXT NOT NULL,
      yes_count INT DEFAULT 0,
      no_count INT DEFAULT 0
    );

    GRANT ALL PRIVILEGES ON survey_db.* TO 'root'@'%' IDENTIFIED BY '';
    FLUSH PRIVILEGES;
